language: node_js
notifications:
  email: false
cache:
  directories:
  - "$HOME/.npm"
jobs:
  include:
  - stage: test
    install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
    script:
    - npm run lint
    - npm run regenerate-schemas
    - npm run validate-schemas
    - npm test
    - npm run coverage
  - stage: NPM develop release
    script:
    - npm version preminor --preid="$TRAVIS_COMMIT"
    deploy:
      provider: npm
      email: chadima.jiri@gmail.com
      skip_cleanup: true
      tag: develop
      api_key: "$NPM_TOKEN"
      on:
        repo: windingtree/wt-booking-api
        branch: master
  - stage: NPM release
    if: tag IS present
    script: echo 'Deploying to NPM...'
    deploy:
      provider: npm
      email: chadima.jiri@gmail.com
      skip_cleanup: true
      api_key: "$NPM_TOKEN"
      on:
        repo: windingtree/wt-booking-api
        tags: true
  - stage: Build and publish docker image
    sudo: true
    services:
    - docker
    install: true
    if: tag IS present
    script:
    - docker build -t windingtree/wt-booking-api:$TRAVIS_BRANCH .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push windingtree/wt-booking-api:$TRAVIS_BRANCH
    - docker tag windingtree/wt-booking-api:$TRAVIS_BRANCH windingtree/wt-booking-api:latest
    - docker push windingtree/wt-booking-api:latest
env:
  global:
  - secure: NDQtIHjlfY7fCoGMljqhv5qOHOwJVnE9N+2NbAYOGzp9H65q6vF1NSGHun+ig6TrdZ+ggpgaNI86WdrendMttbQq718i9/xb8/8qlMEuHsyA3m/CKdmrCy8u0ud42rzXKUDYUmHyVd/Yn7QiGUCGf4wLmo9QOB9im+v7xtJrSswef52f1S9nKSdmt5SgBjGQGTIcKS9ajX7VsQJhwJYxzOuU28EBt459kFJSPfy9T8TL5SEXZL433p64DUj8W27pVw659bS23VtH5OHM+IaFsh/7RksrnQbS9eYCxxHfdp2+piHajThTMBlPiIoumkCImafv54ZCYa8XYEmh/rqVSTg12JdS2jOeiX2rr3tXkcvg1y+WCR4SkvvjdS/uxUAM0iwE/l3M64BSaob925ho9QxoD8eDdbAHduVxFRPAyaxRNtu30opSmfGc/rn73R5knWa0AaRf7HKxbC3E9DIzZnQDNlk3A5GEWzcadMDMgCvKChykpBkts3gGT0BCkKBrGfxUXlB9R7EqE8B6KLq3VF9AFckqYuJHMYO9TpCZDRRpcdyi+KRV/8h7JOCtOue9dL4e0ho2QaNrnu1gmkxxUSDndM0qXDc/W8Vdi71SYRvUDMg7590T4l4HMbxo96CGOh893N5QzgkeGSeYwql3/JCAkfVGC+BLBCP4VzLffJ0=
  - secure: Ja0dm3qmhRGEuVydoeNzHhUgBIebN1bFrOsLzy0feGZqaOBg2mjJxp5Qv0Z6DFWanT8QkZTe7ZqzVTz1NKjKuqSEl/sIkCiY49jQqaj2LMUfiilCjEyoWW/rbyspwTXk/cDMTjzMvGrARvGrG6NQ47gIeietvSWQNPO7qACCLlF62WAWCF7ZC926vl/njFAdZzy0oH63hv8Dp6irwqQfb8vuO/4JlKmecgOJhwsvvu3HTKgFN6RgW1QS7hEhGXHSLnhst0P1IgSnoPZrctw/tpeKF72swfhK5uJDXlyo+cEhi0jvwlKjuwjzJ346++xe5TH5LH3wznctQmCHq/RN5AZVh4cx67Z97L+OIigSdXtEF+WL1c4Cc35K80J0qq8iXYTImU1c/V0K6ZBinvz+0TTVnjo9UjdtBqhAlmLb+EVvQ54IAfkFdh2galLULBuI6NqkPTrwKQT1xY1CcvRY1KzdsZjzXp1wnzTP4zBhPBxjMzRO25ZhzzyxWpy2DmkPNttn5ZeoboYIJ8wskFasu54QrAZeIU1jPOlL3ASt/wwVtmXaO1KZn7auMiElg/N3rWjFq3mfqOCIPRXvNhyCMUK48EuSYQMgsjNRlKblXdi9yb7psVNuQMiODKxMkKP4XN11Ph6dE4cMJSg2wLiscieM54N2X+fRILgZ8dwQhlU=
  - secure: TLN2z1s0kiJ3n2IBZ1OasUYcuCrVj/TZPvkuBSaeWFffQB7kTKEG47cMPZixS/YwKMFbIIvQbQ9ZrvvbnySjDkvvSMY+2ALVU3OCO4Diu/41BQ4D5t1eBdEreLMfOEkeW06XPzKaDnYwNr1gT6mX9CqiOPWuv6eKAxla7/znRlJD4GUvyX2+d0lvHKvqT3AemdFJlrH4s17foUN2iIWSMtWi/Zon6fngBWj7MS3D4TEF8ig2FbxM3DEtsQuZxh/Xg1uyQJVaPpdjgxqYidyHKwSPh0JiO9YFPuYrhktiCVYe3YHgK4KkTlDRmarFVSY1PoRepk41WsCKRzCh5jYZHK+WRRzlmQD6XV/NzIrDKK/FJFLUdOqRc9bgvYqQTRgCOSrqJjlUO2yqzahNfm0uhh+aOHE+t7We9YPW+A3ym287Y4ew6vjdWuOuMNhC4mXhzsEkUS5zNxyOsnmgPo5BNJAGJK1qDu5PTLF2urp+1sEODKxmtSVqrx9ZMJQmNU21Pb/3lojC2eT/bzqattfklWTKQEbUQs/abluoyJytkSqhsM3yOFFOMvCadmHkxHYoehdyu4O1/V+eR67oULI6A9Pfz8UTlygEgm0JfMkxBYZPwy9SKZmNlPEjFKvKl0ezCuW77g1kHPkBalEqzbp76bVhvt2t0QTuP35Vhkzk9u8=
