language: node_js
notifications:
  email: false
cache:
  directories:
  - "$HOME/.npm"
jobs:
  include:
  - stage: test
    install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
    script:
    - npm run lint
    - npm test
    - npm run coverage
  - stage: Build docker image and upload to AWS
    sudo: true
    services:
    - docker
    install: true
    if: tag IS present
    script:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - eval $(aws ecr get-login --no-include-email --region eu-west-1)
    - docker build --build-arg WT_CONFIG=deployment -t wt-booking-api:$TRAVIS_BRANCH .
    - docker tag wt-booking-api:$TRAVIS_BRANCH 029479441096.dkr.ecr.eu-west-1.amazonaws.com/wt-booking-api:$TRAVIS_BRANCH
    - docker push 029479441096.dkr.ecr.eu-west-1.amazonaws.com/wt-booking-api:$TRAVIS_BRANCH
env:
  global:
  - secure: m/jZ/fk/lxnslfxX5OHWuW6zSs/otingNQYxi3zY7g5f8n2nj0jugw2i/YPVnlkbafOyWi84SzzuGcJg/MxE2mGFICZMXZLH5DqLmNZDDYZq3sNQaY/azLI9XsFaeiTl+FjP1RIQ6bSA6zEeITQtPRr439qLditW6GrWidHa30wVOFek1/uD7e2x4z2OS0uG7ISVrS1MWOFhb+CCHXiht5wIih5edMEbTlrm0yg/WTHBuxGzizKcuFtt3+hX47Tn73gRkub/n9BiACPydQn+vhlCYcxHeCKAS7TyLitrXYi+7xtWGMYOWLZ1598dlrFXY6TL06iPuA/3FcH99Vw0nTkUWjfJmYTzarZjO1LnjQGorzS42VoGpJ6x1Fs4T9w4R0iygMDceEe3QyF6EYcohTBbLW/sw0urPe7pnIfdcBIPGxng+O07+ygzgFlkCMv9NwvWs76sUTAVSYCXxIdFOX+krO5ixKQSHRy9cqw6vL/KLr2tI+eavdVq2VdONDdB80azKmsy3qU8sXy9DXoCrrWcMCdYAQTAxjUdiqKdpdVSEPSVJxqmaciz6QcRaNbtX+qDniidvmKGroMIeLTzTN1rHwXJhMtiEy/o8FJi9QkdxRlgCY0i0wiU3TxYuqjlPNptGFVBVxyGjfk8TsvKZLrVskDwWY9yX8y5SE2vgjo=
  - secure: srqtYrftRGlYU6XOCZS9a0CYCkYckLyoL591gi6hr3TH/0ckTi1jGuivQiL0MpWoP/5L+FdVshhNbfX2MvktMrIvJi6lSp+7zklWjQoO91U6U1XV9iZI65TznmaV7vzhbHXSQv3I8alx3aPTjJ923iku97cbDTRzBmhNAjm+hXU5FupXXqWgvw6Jfg+4s7tDzMiHaOT0/UjVnIfTEA9y1g/FoGi5BImS7jp/f9VHjP8xyHIZ87OF2IC9u1WrghX9A9vBtlSpjUx+eoVi8IVEQ56Rr2joLwe8RjoPzhZm1z1jV3G8oZImfA3S8peZIQx+r0Pbeldzvdy9SdAE0RzkfQhyDwBioOIVdESqUSS/7OOu7uKZOTwFreIYl6wR7dXgitiV5riHCMq3K2o2CWZutHgsZC25pFGxrAzdLWMPsVQNxBJWjrWIrob6wTedxnkhEANavJfhxGhnT6o2SnFkgqQDFUM4vUgRl1n0ZKrZh+TRm07wBbfSLAU72Tbf2QcF93/3iD2O9GUHo3y/5DEQlJoHYKVlSHTf1NOhJPsxmk8DzavewU0QhpOfUIL2MiUkBySYO7tO/BDsBwU7rt+a7gTpkeiHF1pcsXfPEJvPO4pAcFrGBO6BzFKyGjyjGQYbRgHwQG1k6yfR0ismMM6Cktt0SfccaoMjr/l9e1P2dLA=
