openapi: 3.0.0
servers:
  - description: Localhost
    url: 'http://localhost:8935'
info:
  description: Interface for hotel booking within Winding Tree.
  version: 'will-be-set-at-runtime'
  title: WT booking API
paths:
  /:
    get:
      summary: API info
      responses:
        '200':
          description: Basic information about this API instance.
          content:
            application/json:
              schema:
                type: object
                properties:
                  docs:
                    type: string
                    description: Link to the API documentation.
                  info:
                    type: string
                    description: Link to more information about the API.
                  version:
                    type: string
                    description: Deployed API version number.
                  config:
                    type: string
                    description: Which config is the API using.
